"""add plugins and themes tables

Revision ID: 87a2ae42cf45
Revises: 20260806_000003
Create Date: 2026-08-27 20:53:43.323321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '87a2ae42cf45'
down_revision: Union[str, None] = '20260806_000003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_polls_created_at'))
        batch_op.drop_index(batch_op.f('ix_polls_is_active'))

    op.drop_table('polls')
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_albums_author_id'))
        batch_op.drop_index(batch_op.f('ix_albums_created_at'))
        batch_op.drop_index(batch_op.f('ix_albums_is_published'))

    op.drop_table('albums')
    op.drop_table('post_tags')
    op.drop_table('user_titles')
    op.drop_table('announcements')
    op.drop_table('search_placeholders')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_author_id'))
        batch_op.drop_index(batch_op.f('ix_activities_created_at'))
        batch_op.drop_index(batch_op.f('ix_activities_is_published'))
        batch_op.drop_index(batch_op.f('ix_activities_type'))

    op.drop_table('activities')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_created_at'))
        batch_op.drop_index(batch_op.f('ix_favorites_post_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))

    op.drop_table('favorites')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_site_id'))
        batch_op.drop_index(batch_op.f('ix_tags_slug'))

    op.drop_table('tags')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_active'))
        batch_op.drop_index(batch_op.f('ix_comments_author_ip_created'))
        batch_op.drop_index(batch_op.f('ix_comments_created_at'))
        batch_op.drop_index(batch_op.f('ix_comments_parent'))
        batch_op.drop_index(batch_op.f('ix_comments_post_active'))
        batch_op.drop_index(batch_op.f('ix_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_comments_post_status_created'))
        batch_op.drop_index(batch_op.f('ix_comments_qq'))
        batch_op.drop_index(batch_op.f('ix_comments_site_id'))
        batch_op.drop_index(batch_op.f('ix_comments_status'))

    op.drop_table('comments')
    with op.batch_alter_table('post_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_revisions_post_id'))

    op.drop_table('post_revisions')
    op.drop_table('hero_slides')
    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_choices_poll_id'))

    op.drop_table('choices')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_qq'))
        batch_op.drop_index(batch_op.f('ix_users_site_id'))
        batch_op.drop_index(batch_op.f('ix_users_token_version'))
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('sites')
    op.drop_table('friend_links')
    with op.batch_alter_table('site_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_configs_key'))

    op.drop_table('site_configs')
    with op.batch_alter_table('visit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_visit_logs_path'))

    op.drop_table('visit_logs')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_author_id'))
        batch_op.drop_index(batch_op.f('ix_posts_content_gin'))
        batch_op.drop_index(batch_op.f('ix_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_posts_post_type'))
        batch_op.drop_index(batch_op.f('ix_posts_published_at'))
        batch_op.drop_index(batch_op.f('ix_posts_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_posts_series_id'))
        batch_op.drop_index(batch_op.f('ix_posts_site_id'))
        batch_op.drop_index(batch_op.f('ix_posts_slug'))
        batch_op.drop_index(batch_op.f('ix_posts_status'))
        batch_op.drop_index(batch_op.f('ix_posts_status_created'))
        batch_op.drop_index(batch_op.f('ix_posts_status_pinned_published'))
        batch_op.drop_index(batch_op.f('ix_posts_status_published'))
        batch_op.drop_index(batch_op.f('ix_posts_title_gin'))

    op.drop_table('posts')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_album_id'))
        batch_op.drop_index(batch_op.f('ix_photos_created_at'))

    op.drop_table('photos')
    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_private_messages_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_private_messages_sender_id'))

    op.drop_table('private_messages')
    with op.batch_alter_table('post_view_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_view_histories_user_post'))

    op.drop_table('post_view_histories')
    with op.batch_alter_table('favorite_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_folders_user_id'))

    op.drop_table('favorite_folders')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_site_id'))

    op.drop_table('media')
    op.drop_table('user_preferences')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_slug'))

    op.drop_table('pages')
    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_metrics_created_at'))

    op.drop_table('performance_metrics')
    op.drop_table('navigations')
    op.drop_table('webhook_endpoints')
    with op.batch_alter_table('content_type_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_type_definitions_key'))
        batch_op.drop_index(batch_op.f('ix_content_type_definitions_site_id'))

    op.drop_table('content_type_definitions')
    with op.batch_alter_table('captcha_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_captcha_records_key'))

    op.drop_table('captcha_records')
    with op.batch_alter_table('comment_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_reactions_comment_id'))
        batch_op.drop_index(batch_op.f('ix_comment_reactions_unique'))
        batch_op.drop_index(batch_op.f('ix_comment_reactions_user_id'))

    op.drop_table('comment_reactions')
    with op.batch_alter_table('guestbook_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guestbook_author_ip_created'))
        batch_op.drop_index(batch_op.f('ix_guestbook_entries_created_at'))
        batch_op.drop_index(batch_op.f('ix_guestbook_entries_is_pinned'))
        batch_op.drop_index(batch_op.f('ix_guestbook_entries_qq'))
        batch_op.drop_index(batch_op.f('ix_guestbook_entries_status'))
        batch_op.drop_index(batch_op.f('ix_guestbook_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_guestbook_status_deleted_pinned_created'))

    op.drop_table('guestbook_entries')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))
        batch_op.drop_index(batch_op.f('ix_categories_site_id'))
        batch_op.drop_index(batch_op.f('ix_categories_slug'))

    op.drop_table('categories')
    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('trash_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trash_items_resource_type'))

    op.drop_table('trash_items')
    with op.batch_alter_table('content_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_types_key'))
        batch_op.drop_index(batch_op.f('ix_content_types_site_id'))

    op.drop_table('content_types')
    with op.batch_alter_table('post_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_series_slug'))

    op.drop_table('post_series')
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_logs_action'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_user_id'))

    op.drop_table('operation_logs')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_expires'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('content_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_fields_definition_id'))
        batch_op.drop_index(batch_op.f('ix_content_fields_site_id'))

    op.drop_table('content_fields')
    op.drop_table('post_likes')
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_votes_choice_id'))
        batch_op.drop_index(batch_op.f('ix_votes_poll_choice'))
        batch_op.drop_index(batch_op.f('ix_votes_poll_id'))
        batch_op.drop_index(batch_op.f('ix_votes_user_poll'))

    op.drop_table('votes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """回退数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('poll_id', sa.INTEGER(), nullable=False),
    sa.Column('choice_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['choice_id'], ['choices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_votes_user_poll'), ['user_id', 'poll_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_poll_id'), ['poll_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_poll_choice'), ['poll_id', 'choice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_choice_id'), ['choice_id'], unique=False)

    op.create_table('post_likes',
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_table('content_fields',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('site_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('definition_id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=50), nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), nullable=False),
    sa.Column('field_type', sa.VARCHAR(length=20), server_default=sa.text("'text'"), nullable=False),
    sa.Column('options', sqlite.JSON(), nullable=True),
    sa.Column('placeholder', sa.VARCHAR(length=200), nullable=True),
    sa.Column('required', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('order_index', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('help_text', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['content_type_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_fields_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_fields_definition_id'), ['definition_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_expires'), ['user_id', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token'), ['token'], unique=1)

    op.create_table('operation_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('resource_id', sa.INTEGER(), nullable=True),
    sa.Column('detail', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True),
    sa.Column('request_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('request_method', sa.VARCHAR(length=10), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('error_code', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_action'), ['action'], unique=False)

    op.create_table('post_series',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sqlite.JSON(), nullable=False),
    sa.Column('description', sqlite.JSON(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cover_image', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_series_slug'), ['slug'], unique=1)

    op.create_table('content_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('icon', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('fields', sqlite.JSON(), nullable=False),
    sa.Column('site_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'key', name=op.f('uq_content_types_site_key'))
    )
    with op.batch_alter_table('content_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_types_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_types_key'), ['key'], unique=False)

    op.create_table('trash_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('resource_id', sa.INTEGER(), nullable=False),
    sa.Column('resource_data', sa.TEXT(), nullable=False),
    sa.Column('deleted_by_id', sa.INTEGER(), nullable=True),
    sa.Column('auto_delete_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trash_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trash_items_resource_type'), ['resource_type'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('endpoint_id', sa.INTEGER(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('payload', sa.TEXT(), nullable=False),
    sa.Column('status_code', sa.INTEGER(), nullable=True),
    sa.Column('response_body', sa.TEXT(), nullable=True),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('delivered_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sqlite.JSON(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sqlite.JSON(), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('color', sa.VARCHAR(length=20), nullable=False),
    sa.Column('cover_image', sa.VARCHAR(length=500), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('site_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=1)
        batch_op.create_index(batch_op.f('ix_categories_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)

    op.create_table('guestbook_entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('author_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('author_email', sa.VARCHAR(length=254), nullable=True),
    sa.Column('author_website', sa.VARCHAR(length=200), nullable=True),
    sa.Column('author_ip', sa.VARCHAR(length=64), nullable=True),
    sa.Column('author_user_agent', sa.VARCHAR(length=200), nullable=True),
    sa.Column('qq', sa.VARCHAR(length=20), nullable=True),
    sa.Column('github', sa.VARCHAR(length=64), nullable=True),
    sa.Column('avatar_source', sa.VARCHAR(length=16), server_default=sa.text("'auto'"), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('is_pinned', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('likes_count', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guestbook_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guestbook_status_deleted_pinned_created'), ['status', 'deleted_at', 'is_pinned', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_guestbook_entries_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guestbook_entries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_guestbook_entries_qq'), ['qq'], unique=False)
        batch_op.create_index(batch_op.f('ix_guestbook_entries_is_pinned'), ['is_pinned'], unique=False)
        batch_op.create_index(batch_op.f('ix_guestbook_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_guestbook_author_ip_created'), ['author_ip', 'created_at'], unique=False)

    op.create_table('comment_reactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('comment_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('emoji', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_reactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_reactions_unique'), ['comment_id', 'user_id', 'emoji'], unique=1)
        batch_op.create_index(batch_op.f('ix_comment_reactions_comment_id'), ['comment_id'], unique=False)

    op.create_table('captcha_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=32), nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('captcha_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_captcha_records_key'), ['key'], unique=1)

    op.create_table('content_type_definitions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('site_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('key', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('template', sa.VARCHAR(length=50), nullable=True),
    sa.Column('has_archive', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('order_index', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('content_type_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_type_definitions_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_type_definitions_key'), ['key'], unique=False)

    op.create_table('webhook_endpoints',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('secret', sa.VARCHAR(length=100), nullable=True),
    sa.Column('events', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('navigations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sqlite.JSON(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=200), nullable=False),
    sa.Column('icon', sa.VARCHAR(length=100), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=20), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('target_blank', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['navigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_metrics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=500), nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status_code', sa.INTEGER(), nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True),
    sa.Column('ip', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_metrics_created_at'), ['created_at'], unique=False)

    op.create_table('pages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sqlite.JSON(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sqlite.JSON(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_slug'), ['slug'], unique=1)

    op.create_table('user_preferences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('public_profile', sa.BOOLEAN(), nullable=False),
    sa.Column('show_email', sa.BOOLEAN(), nullable=False),
    sa.Column('show_posts', sa.BOOLEAN(), nullable=False),
    sa.Column('show_comments', sa.BOOLEAN(), nullable=False),
    sa.Column('show_stats', sa.BOOLEAN(), nullable=False),
    sa.Column('show_social_links', sa.BOOLEAN(), nullable=False),
    sa.Column('theme', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('media',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file', sa.VARCHAR(length=500), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('alt_text', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('uploaded_by_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('site_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('width', sa.INTEGER(), nullable=True),
    sa.Column('height', sa.INTEGER(), nullable=True),
    sa.Column('sizes', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_site_id'), ['site_id'], unique=False)

    op.create_table('favorite_folders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favorite_folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_folders_user_id'), ['user_id'], unique=False)

    op.create_table('post_view_histories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('viewed_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_view_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_view_histories_user_post'), ['user_id', 'post_id'], unique=1)

    op.create_table('private_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_private_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_private_messages_recipient_id'), ['recipient_id'], unique=False)

    op.create_table('photos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('album_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_album_id'), ['album_id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sqlite.JSON(), nullable=False),
    sa.Column('subtitle', sqlite.JSON(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=200), nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('source_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('audio', sa.VARCHAR(length=500), nullable=True),
    sa.Column('video', sa.VARCHAR(length=500), nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('content', sqlite.JSON(), nullable=False),
    sa.Column('excerpt', sqlite.JSON(), nullable=True),
    sa.Column('cover_image', sa.VARCHAR(length=500), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('visibility', sa.VARCHAR(length=10), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=True),
    sa.Column('views', sa.INTEGER(), nullable=False),
    sa.Column('is_pinned', sa.BOOLEAN(), nullable=False),
    sa.Column('allow_comments', sa.BOOLEAN(), nullable=False),
    sa.Column('meta_title', sqlite.JSON(), nullable=True),
    sa.Column('meta_description', sqlite.JSON(), nullable=True),
    sa.Column('meta_keywords', sqlite.JSON(), nullable=True),
    sa.Column('series_id', sa.INTEGER(), nullable=True),
    sa.Column('series_order', sa.INTEGER(), nullable=False),
    sa.Column('encrypted_content', sqlite.JSON(), nullable=True),
    sa.Column('encryption_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('encryption_hint', sa.VARCHAR(length=200), nullable=True),
    sa.Column('encryption_salt', sa.VARCHAR(length=128), nullable=True),
    sa.Column('encryption_verifier', sa.VARCHAR(length=256), nullable=True),
    sa.Column('encryption_algorithm', sa.VARCHAR(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('site_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('post_type', sa.VARCHAR(length=50), server_default=sa.text("'post'"), nullable=False),
    sa.Column('meta_fields', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['post_series.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_title_gin'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_status_published'), ['status', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_status_pinned_published'), ['status', 'is_pinned', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_status_created'), ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_slug'), ['slug'], unique=1)
        batch_op.create_index(batch_op.f('ix_posts_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_post_type'), ['post_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_content_gin'), ['content'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_author_id'), ['author_id'], unique=False)

    op.create_table('visit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), nullable=False),
    sa.Column('ip', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True),
    sa.Column('referer', sa.VARCHAR(length=500), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('status_code', sa.INTEGER(), nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_logs_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('site_configs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_configs_key'), ['key'], unique=1)

    op.create_table('friend_links',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sqlite.JSON(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('description', sqlite.JSON(), nullable=True),
    sa.Column('logo', sa.VARCHAR(length=500), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('target_blank', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('theme_key', sa.VARCHAR(length=64), server_default=sa.text("'default'"), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('order_index', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('locale', sa.VARCHAR(length=20), nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=64), server_default=sa.text("'Asia/Shanghai'"), nullable=False),
    sa.Column('site_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('avatar', sa.VARCHAR(length=500), nullable=True),
    sa.Column('cover_image', sa.VARCHAR(length=500), nullable=True),
    sa.Column('nickname', sa.VARCHAR(length=50), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('website', sa.VARCHAR(length=200), nullable=True),
    sa.Column('github', sa.VARCHAR(length=200), nullable=True),
    sa.Column('qq', sa.VARCHAR(length=20), nullable=True),
    sa.Column('avatar_source', sa.VARCHAR(length=16), server_default=sa.text("'auto'"), nullable=False),
    sa.Column('title_id', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=False),
    sa.Column('is_banned', sa.BOOLEAN(), nullable=False),
    sa.Column('token_version', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('locked_until', sa.DATETIME(), nullable=True),
    sa.Column('notify_by_email', sa.BOOLEAN(), server_default=sa.text("'true'"), nullable=False),
    sa.Column('failed_login_attempts', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'subscriber'"), nullable=False),
    sa.Column('site_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['user_titles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('ix_users_token_version'), ['token_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_qq'), ['qq'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=1)

    op.create_table('choices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('poll_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=200), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_choices_poll_id'), ['poll_id'], unique=False)

    op.create_table('hero_slides',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('subtitle', sa.TEXT(), nullable=True),
    sa.Column('media_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('media_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('poster_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('overlay_opacity', sa.INTEGER(), nullable=False),
    sa.Column('overlay_color', sa.VARCHAR(length=20), nullable=False),
    sa.Column('cta_text', sa.TEXT(), nullable=True),
    sa.Column('cta_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('cta_secondary_text', sa.TEXT(), nullable=True),
    sa.Column('cta_secondary_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('text_align', sa.VARCHAR(length=10), nullable=False),
    sa.Column('text_color', sa.VARCHAR(length=10), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_revisions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('revision_number', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('excerpt', sa.TEXT(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('change_summary', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_revisions_post_id'), ['post_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('author_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('author_email', sa.VARCHAR(length=254), nullable=True),
    sa.Column('author_website', sa.VARCHAR(length=200), nullable=True),
    sa.Column('author_ip', sa.VARCHAR(length=64), nullable=True),
    sa.Column('author_user_agent', sa.VARCHAR(length=200), nullable=True),
    sa.Column('qq', sa.VARCHAR(length=20), nullable=True),
    sa.Column('github', sa.VARCHAR(length=64), nullable=True),
    sa.Column('avatar_source', sa.VARCHAR(length=16), server_default=sa.text("'auto'"), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('likes_count', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('is_pinned', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('reported_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('site_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_qq'), ['qq'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_post_status_created'), ['post_id', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_post_active'), ['post_id', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_parent'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_author_ip_created'), ['author_ip', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_active'), ['active'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sqlite.JSON(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), nullable=False),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('site_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_slug'), ['slug'], unique=1)
        batch_op.create_index(batch_op.f('ix_tags_site_id'), ['site_id'], unique=False)

    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('folder_id', sa.INTEGER(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['favorite_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_created_at'), ['created_at'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sqlite.JSON(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), nullable=False),
    sa.Column('likes_count', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_author_id'), ['author_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), nullable=False),
    sa.Column('actor_id', sa.INTEGER(), nullable=False),
    sa.Column('verb', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('object_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sqlite.JSON(), nullable=False),
    sa.Column('message', sqlite.JSON(), nullable=False),
    sa.Column('level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)

    op.create_table('search_placeholders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sqlite.JSON(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_dismissible', sa.BOOLEAN(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_titles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), nullable=False),
    sa.Column('icon', sa.TEXT(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_tags',
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.create_table('albums',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('cover', sa.VARCHAR(length=500), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text("'true'"), nullable=False),
    sa.Column('photo_count', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_albums_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_albums_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_albums_author_id'), ['author_id'], unique=False)

    op.create_table('polls',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('allow_multiple', sa.BOOLEAN(), nullable=False),
    sa.Column('show_results', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_polls_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_polls_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
