/**
 * robots.txt (Nitro BFF → FastAPI /seo/robots.txt)
 *
 * 后端连接单源：server/utils/ssr#resolveBackendEndpoint。
 * 上游不可达时返回回退内容；Sitemap 行只在配置了 SITE_URL 时输出。
 */

/**
 * 解析对外站点根 URL：**只**信任 runtime(.public).siteUrl 配置，绝不从
 * x-forwarded-host / Host 请求头推导——伪造 Host 可把攻击者域名写进 Sitemap 行，
 * 并被下面的 s-maxage=3600 缓存投毒（SEO/缓存双层污染）。缺配置返回 ''（跳过 Sitemap 行）。
 */
function resolveConfiguredOrigin(runtime: ReturnType<typeof useRuntimeConfig>): string {
  const configured = (runtime as unknown as { siteUrl?: string }).siteUrl
    || (runtime.public as unknown as { siteUrl?: string })?.siteUrl
  return configured ? String(configured).replace(/\/$/, '') : ''
}

export default defineEventHandler((event) => {
  const runtime = useRuntimeConfig(event)
  const target = resolveBackendEndpoint(runtime, '/seo/robots.txt')
  const origin = resolveConfiguredOrigin(runtime)

  const fallback = `# robots.txt — generated by Rosetta Blog
User-agent: *
Allow: /

Disallow: /admin/
Disallow: /api/
Disallow: /login
Disallow: /register
Disallow: /oobe
Disallow: /search
${origin ? `\nSitemap: ${origin}/sitemap.xml\n` : ''}`

  return proxyUpstreamText(event, target, fallback, {
    accept: 'text/plain',
    contentType: 'text/plain; charset=utf-8',
    cacheControl: 'public, max-age=3600, s-maxage=3600'
  })
})
