/**
 * robots.txt (Nitro BFF → FastAPI /seo/robots.txt)
 *
 * 后端连接单源：server/utils/ssr#resolveBackendEndpoint。
 * 上游不可达时返回带「绝对 Sitemap URL」的回退内容。
 */

import type { H3Event } from 'h3'

/** 解析对外站点根 URL：优先 SITE_URL 配置，否则从请求头推导。 */
function resolveOrigin(event: H3Event, runtime: ReturnType<typeof useRuntimeConfig>): string {
  const configured = runtime.siteUrl || runtime.public?.siteUrl
  if (configured) return String(configured).replace(/\/$/, '')
  const host = getRequestHost(event, { xForwardedHost: true })
  const protocol = getRequestProtocol(event, { xForwardedProto: true })
  return `${protocol}://${host}`
}

export default defineEventHandler((event) => {
  const runtime = useRuntimeConfig(event)
  const target = resolveBackendEndpoint(runtime, '/seo/robots.txt')
  const origin = resolveOrigin(event, runtime)

  const fallback = `# robots.txt — generated by Rosetta Blog
User-agent: *
Allow: /

Disallow: /admin/
Disallow: /api/
Disallow: /login
Disallow: /register
Disallow: /oobe
Disallow: /search

Sitemap: ${origin}/sitemap.xml
`

  return proxyUpstreamText(event, target, fallback, {
    accept: 'text/plain',
    contentType: 'text/plain; charset=utf-8',
    cacheControl: 'public, max-age=3600, s-maxage=3600'
  })
})
